### ISSUE TITLE
interface description metrics / junos_interface_description

### ISSUE THREAD

**Issue by cjewgit** [tynany/junos_exporter#11]
Hi,

I was wondering why the interface descriptions were moved into its own metric?

In my very old version of junos_exporter, I find all interface descriptions attached to all interface metrics, example:

```
junos_interface_input_bps{interface="et-0/0/30",peer="Logix",peerasn="25956",rack="",type="internet"}
```

which allows me to query it like this across the board globally via promql

```
junos_interface_input_bps{type="internet"}
```

Now I get a new metric called junos_interface_description, example for the same port:

```
junos_interface_description{interface="et-0/0/30",peer="Logix",peerasn="25956",rack="",type="internet"} 1
```

My promql to map junos_interface_input_bps to this based on descriptions now looks like this:

```
(
  sum by(ciname, interface) (junos_interface_input_bps{ciname=~".*"})
)
  + on(ciname, interface) group_left(type, peer, peerasn, rack)
(
  junos_interface_description{ciname=~".*", type="internet"}
)
```

I measured the old and new way and there was no difference in speed for me. Any chance you could let me know why this was changed or if I am missing something here?

Thank you
Chris

**Comment by tynany** [comment]
In older versions, the `type` field in a JSON formatted interface description was added to all interface metrics under the `type` label. This actually goes against Prometheus best practices which recommend label values never change (https://prometheus.io/docs/practices/naming/#labels), but it was done for convenience anyway.

A new use case then presented itself -- using more fields from a JSON formatted interface description. For example, adding the circuit ID and carrier as a label so they can be used in Prometheus alerts/queries. This is achieved today using the `interface_description_keys` config. The poor practice could have continued by adding these new labels to ALL interface metrics, but that would lead to even more cardinality bloat -- every time a JSON field is added/removed/updated it would result in a new metric and you'd lose the history of that interface metric. Instead, interface description labels were moved to the convenience metric `junos_interface_description`. No functionality is lost, but I agree, queries can become more complex as you've highlighted above.

If you feel strongly, I can implement a flag that adds the description keys (i.e. under `interface_description_keys`) as interface labels as well as to the `junos_interface_description` metric. Let me know.

**Comment by cjewgit** [comment]
Ah okay, that makes perfect sense. Thank you for letting me know.

I can work with it, I was just wondering for the reason behind it.

Thank you! Closing.
