### ISSUE TITLE
IPsec collector

### ISSUE THREAD

**Issue by cjewgit** [tynany/junos_exporter#9]
Hi,

I was wondering if you guys are open to a ipsec collector feature for a SRX? I created a very simple one and would like to put in a PR for it. Its very basic and returns the following prom metric

junos_ipsec_tunnel_status_up{saremotegateway="<peer IP>",satunnelindex="<unique index>"} 0 or 1, 0 = inactive, 1 = active

Please let me know if this feature is welcome and I would create the PR for it.

Thanks

**Comment by tynany** [comment]
Absolutely. Feel free to submit a PR. Thanks!

**Comment by cjewgit** [comment]
Thank you. Added the PR. Closing the issue.

**Comment by tynany** [comment]
Released in [v0.1.10](https://github.com/tynany/junos_exporter/releases/tag/v0.1.10)
